### PR TITLE
link to open Issues and Pull requests of project

### PR DESCRIPTION
**Pull request by jukzi**
for eclipse-platform organization

### CODE REVIEW

**Comment by jukzi** [comment]
@mickaelistria  @akurtakov WDYT? i don't know a better way to get a overview across all subprojects.

**Comment by akurtakov** [comment]
I like the idea of having these links.

**Comment by akurtakov** [comment]
Weirdly enough I see the links in the compare but not when seeing the repo itself. Maybe it's some caching issue.

**Comment by jukzi** [comment]
i see it :-)

**Comment by akurtakov** [comment]
All good in this case.

**Pull request merged**
